###############################
# Intermediate-song-importer
###############################
FROM adoptopenjdk/openjdk11:jre-11.0.6_10-alpine
ENV SRV_HOME      /srv
ENV SRV_DIST_DIR  /srv-dist

COPY target/*-dist.tar.gz  /importer.tar.gz

RUN mkdir /srv/temp \
	&& tar zxvf /importer.tar.gz -C /srv/temp \
	&& rm -rf /importer.tar.gz \
	&& mv /srv/temp/intermediate-song-importer* /srv/temp/something \
	&& mv /srv/temp/something/* /srv \
	&& rm -rf /srv/temp \
	&& apk add bash

# Set working directory for convenience with interactive usage
WORKDIR $SRV_HOME
